# Params could be placeholders in form ${STORAGE_STRATEGY} in which case they will take the value from env variables
storageStrategy: inMemory

mysql:
  connections: 10
  host: localhost
  user: toggly
  password: toggly
  database: toggly
  table: feature